#------------------------------------------------------------
# LOG
#------------------------------------------------------------

# 核心：全局只输出 WARN + ERROR，彻底关闭 INFO/DEBUG 刷屏
quarkus.log.level=INFO

# 强制关闭控制台多余输出（非常重要）
quarkus.log.console.level=INFO

# 彻底关闭 HTTP 访问日志（避免再刷请求日志）
quarkus.http.access-log.enabled=false